#include <algorithm>
#include <cmath>
#include <vector>

#include "bpmcore/OnsetDetector.hpp"
#include "catch_amalgamated.hpp"

namespace {

// Builds a mono buffer with short sine-burst clicks at an exact period,
// mirroring the synthetic click tracks generated by generate_click_tracks.py.
std::vector<float> makeClickTrain(double sampleRate, double bpm, double durationSec) {
    const size_t n = static_cast<size_t>(durationSec * sampleRate);
    std::vector<float> samples(n, 0.0f);

    const double periodSec = 60.0 / bpm;
    const int clickLen = static_cast<int>(0.015 * sampleRate);
    const double clickFreq = 1000.0;

    for (double t = 0.0; t < durationSec; t += periodSec) {
        int start = static_cast<int>(t * sampleRate);
        for (int i = 0; i < clickLen && start + i < static_cast<int>(n); ++i) {
            double envelope = std::pow(1.0 - static_cast<double>(i) / clickLen, 2.0);
            double phase = 2.0 * M_PI * clickFreq * (static_cast<double>(i) / sampleRate);
            samples[start + i] = static_cast<float>(envelope * std::sin(phase));
        }
    }
    return samples;
}

} // namespace

TEST_CASE("OnsetDetector produces sharp peaks at click positions", "[onset]") {
    const double sampleRate = 44100.0;
    const double bpm = 120.0;
    auto samples = makeClickTrain(sampleRate, bpm, 8.0);

    bpmcore::OnsetDetector detector(sampleRate);
    detector.feed(samples.data(), samples.size());

    const auto& env = detector.envelope();
    REQUIRE(env.values.size() > 10);

    const double expectedFrames = (60.0 / bpm) / env.hopSeconds;

    // Greedy non-max suppression: take the strongest remaining frame, forbid
    // any other peak within half a beat period of it, repeat. This picks one
    // peak per click even if a click's onset energy ripples across a couple
    // of adjacent STFT frames (a real detector never emits an isolated,
    // one-frame-wide spike for a single physical transient).
    std::vector<size_t> order(env.values.size());
    for (size_t i = 0; i < order.size(); ++i) order[i] = i;
    std::sort(order.begin(), order.end(),
              [&](size_t a, size_t b) { return env.values[a] > env.values[b]; });

    std::vector<int> peaks;
    const int minSpacing = static_cast<int>(expectedFrames / 2.0);
    for (size_t idx : order) {
        if (env.values[idx] <= 0.0f) break;
        bool tooClose = false;
        for (int p : peaks) {
            if (std::abs(p - static_cast<int>(idx)) < minSpacing) {
                tooClose = true;
                break;
            }
        }
        if (!tooClose) {
            peaks.push_back(static_cast<int>(idx));
        }
    }
    std::sort(peaks.begin(), peaks.end());

    // Expect roughly one peak per beat (period 0.5s at 120 BPM over 8s -> ~16 beats).
    REQUIRE(peaks.size() >= 10);

    // Consecutive peaks should be spaced close to the beat period in frames.
    // A one-hop-frame tolerance beyond rounding is allowed: the true period
    // (43.07 frames here) isn't an integer number of hops, so consecutive
    // raw peak-to-peak spacing legitimately alternates by +/-1 frame; the
    // sub-frame refinement in BpmAnalyzer (not exercised by this detector-only
    // test) is what recovers the precise period.
    for (size_t i = 1; i < peaks.size(); ++i) {
        double delta = peaks[i] - peaks[i - 1];
        REQUIRE(delta == Catch::Approx(expectedFrames).margin(3.0));
    }
}

TEST_CASE("OnsetDetector resets cleanly", "[onset]") {
    const double sampleRate = 44100.0;
    auto samples = makeClickTrain(sampleRate, 120.0, 4.0);

    bpmcore::OnsetDetector detector(sampleRate);
    detector.feed(samples.data(), samples.size());
    REQUIRE(!detector.envelope().values.empty());

    detector.reset();
    REQUIRE(detector.envelope().values.empty());
}
